CREATE DATABASE IF NOT EXISTS szkc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE szkc;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  middleName VARCHAR(100) NULL,
  lastName VARCHAR(100) NOT NULL,
  ext VARCHAR(20) NULL,
  email VARCHAR(255) NOT NULL,
  passwordHash VARCHAR(10) NOT NULL,
  role ENUM('admin', 'superadmin') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB;
