-- Run this file in the Supabase SQL Editor.
-- Database and schema creation are managed by Supabase.
-- Column names intentionally use camelCase to match the application format.

-- Rename columns if the earlier snake_case version of this schema was already run.
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'first_name') then
    alter table public.users rename column first_name to "firstName";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'middle_name') then
    alter table public.users rename column middle_name to "middleName";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'last_name') then
    alter table public.users rename column last_name to "lastName";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'password_hash') then
    alter table public.users rename column password_hash to "passwordHash";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'created_at') then
    alter table public.users rename column created_at to "createdAt";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'users' and column_name = 'updated_at') then
    alter table public.users rename column updated_at to "updatedAt";
  end if;
end
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "firstName" text not null check (char_length("firstName") between 1 and 100),
  "middleName" text check ("middleName" is null or char_length("middleName") <= 100),
  "lastName" text not null check (char_length("lastName") between 1 and 100),
  ext text check (ext is null or char_length(ext) <= 20),
  email text not null,
  "passwordHash" text not null,
  role text not null default 'admin' check (role in ('admin', 'superadmin')),
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_users_email_lower
  on public.users (lower(email));

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

-- User records are accessed by server-side API routes using the server secret.
-- Do not add a public read/insert policy for this table.
alter table public.users enable row level security;
revoke all on table public.users from anon, authenticated;
